import { StyleSheet } from 'react-native';
import { THEME } from '../../theme';

/**
 * Styles partagés par GameScreen et ses sous-écrans (src/screens/game/*).
 * Extrait de GameScreen.tsx lors du découpage en sous-composants —
 * comportement et valeurs inchangés, seul l'emplacement a bougé.
 */

// 🎨 PALETTE MODERNE & ÉPURÉE (Design élégant et intuitif)
export const COLORS = {
  bg: THEME.colors.bgTertiary,
  bgDark: THEME.colors.bgPrimary,
  primary: THEME.colors.primaryDark,
  primaryLight: THEME.colors.primaryLight,
  primaryDark: THEME.colors.primaryDark,
  accent: THEME.colors.secondary,
  accentLight: THEME.colors.secondaryLight,
  text: THEME.colors.textPrimary,
  textLight: THEME.colors.textSecondary,
  textMuted: THEME.colors.gray200,
  surface: THEME.colors.bgSecondary,
  surfaceHover: THEME.colors.bgTertiary,
  border: THEME.colors.border,
  success: THEME.colors.success,
  error: THEME.colors.error,
  warning: THEME.colors.warning,
};

export const styles = StyleSheet.create({
  containerGradient: {
    flex: 1,
  },
  
  // Mode Selection
  modeSelectionContainer: {
    flex: 1,
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  titleMain: {
    fontSize: 42,
    fontWeight: '900',
    color: THEME.colors.primary,
    marginBottom: 0,
    letterSpacing: 2,
    textAlign: 'center',
  },
  titleSub: {
    fontSize: 42,
    fontWeight: '900',
    color: THEME.colors.primaryLight,
    marginBottom: 12,
    letterSpacing: 2,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 14,
    color: THEME.colors.textSecondary,
    marginBottom: 32,
    letterSpacing: 0.5,
    textAlign: 'center',
    fontWeight: '500',
  },
  modesWrapper: {
    width: '100%',
    gap: 14,
    maxWidth: 340,
    alignSelf: 'center',
  },
  modeButton: {
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 6,
    shadowColor: THEME.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    width: '100%',
  },
  modeButtonDisabled: {
    opacity: 0.45,
  },
  offlineBanner: {
    backgroundColor: THEME.colors.warningLight,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignSelf: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: THEME.colors.warning,
  },
  offlineText: {
    color: THEME.colors.warning,
    fontWeight: '700',
  },

  // Gradient wrapper used for mode buttons
  modeBtnGradient: {
    paddingVertical: 22,
    paddingHorizontal: 20,
    alignItems: 'center',
    gap: 10,
    borderRadius: 12,
  },

  modeIcon: {
    fontSize: 40,
  },
  modeButtonText: {
    fontSize: 17,
    fontWeight: '800',
    color: THEME.colors.white,
    letterSpacing: 0.8,
  },
  modeDesc: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.9)',
    fontWeight: '400',
  },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(30, 41, 59, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  modalCenterContainer: {
    width: '100%',
    maxWidth: 360,
    maxHeight: '80%',
  },
  modalContentWrapper: {
    width: '100%',
    maxHeight: '85%',
  },
  modalContent: {
    borderRadius: 28,
    padding: 32,
    gap: 18,
    elevation: 10,
    shadowColor: THEME.colors.secondary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    width: '100%',
    maxWidth: 340,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: THEME.colors.primary,
    textAlign: 'center',
    letterSpacing: 1,
    marginBottom: 12,
  },
  modalInput: {
    backgroundColor: THEME.colors.bgSecondary,
    borderWidth: 2,
    borderColor: THEME.colors.primary,
    borderRadius: 14,
    paddingVertical: 18,
    paddingHorizontal: 18,
    fontSize: 16,
    color: THEME.colors.textPrimary,
  },
  arenaInput: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 12,
    fontSize: 14,
    color: COLORS.text,
    marginBottom: 8,
  },
  createBtnFull: {
    borderRadius: 14,
    overflow: 'hidden',
    elevation: 6,
    shadowColor: THEME.colors.success,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  createBtnDisabled: {
    opacity: 0.5,
  },
  joinBtnFull: {
    borderRadius: 14,
    overflow: 'hidden',
    elevation: 6,
    shadowColor: THEME.colors.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  btnGradientFull: {
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: THEME.colors.white,
    letterSpacing: 0.8,
  },
  modalCloseBtn: {
    paddingVertical: 12,
    marginTop: 6,
  },
  modalCloseText: {
    fontSize: 13,
    color: THEME.colors.gray200,
    textAlign: 'center',
    fontWeight: '700',
  },

  // Game Screen
  gameContainer: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 12,
    flexDirection: 'column',
  },
  mainContent: {
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  leftPanel: {
    flex: 0.45,
    gap: 6,
  },
  rightPanel: {
    flex: 0.55,
    flexDirection: 'column',
    gap: 8,
  },
  bottomSection: {
    gap: 8,
  },
  actionButtonsRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  submitButtonContainer: {
    flex: 1,
  },
  submitButton: {
    borderRadius: 10,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: THEME.colors.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  submitGradient: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  submitButtonDisabled: {
    elevation: 0,
    shadowOpacity: 0,
  },
  submitButtonText: {
    fontSize: 18,
    fontWeight: '800',
    color: THEME.colors.bgSecondary,
  },
  abandonButtonSmall: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: THEME.colors.error,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: THEME.colors.error,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  abandonButtonSmallText: {
    fontSize: 20,
  },
  resetButtonSmall: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: THEME.colors.success,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: THEME.colors.success,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  resetButtonSmallText: {
    fontSize: 20,
  },
  switchPlayerButton: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: THEME.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: THEME.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  switchPlayerButtonText: {
    fontSize: 20,
  },
  gameHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: THEME.colors.bgTertiary,
  },
  agentInfo: {
    flex: 1,
  },
  agentLabel: {
    fontSize: 10,
    color: THEME.colors.gray200,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  agentName: {
    fontSize: 14,
    fontWeight: '800',
    color: THEME.colors.secondary,
  },
  modeInfoGame: {
    flex: 1,
    alignItems: 'center',
  },
  modeBadge: {
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  modeLabelGame: {
    fontSize: 10,
    fontWeight: '800',
    color: THEME.colors.white,
    letterSpacing: 0.8,
  },
  difficultyBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  difficultyBadgeText: {
    fontSize: 12,
    marginLeft: 0,
  },
  menuButton: {
    width: 38,
    height: 38,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: THEME.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: THEME.colors.bgSecondary,
    elevation: 2,
    shadowColor: THEME.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
  },
  menuButtonText: {
    fontSize: 18,
  },

  // Current Code Input
  currentCodeSection: {
    backgroundColor: THEME.colors.bgSecondary,
    borderWidth: 2,
    borderColor: THEME.colors.primaryLight,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    alignItems: 'center',
    gap: 6,
    elevation: 3,
    shadowColor: THEME.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  currentCodeLabel: {
    fontSize: 10,
    color: THEME.colors.primary,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  currentCodeDisplay: {
    fontSize: 20,
    fontWeight: '900',
    color: THEME.colors.primary,
    letterSpacing: 4,
    fontFamily: 'monospace',
  },
  lockedPositionsHint: {
    fontSize: 11,
    color: THEME.colors.primary,
    fontWeight: '700',
    marginTop: 8,
    textAlign: 'center',
    backgroundColor: THEME.colors.bgTertiary,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: THEME.colors.secondaryLight,
  },
  abandonButton: {
    backgroundColor: THEME.colors.error,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    marginBottom: 8,
    elevation: 3,
    shadowColor: THEME.colors.error,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  abandonButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: THEME.colors.bgSecondary,
    letterSpacing: 0.8,
  },

  // Code Input
  codeInputBox: {
    backgroundColor: THEME.colors.bgSecondary,
    borderWidth: 2,
    borderColor: THEME.colors.primaryLight,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 14,
    alignItems: 'center',
    gap: 6,
    elevation: 4,
    shadowColor: THEME.colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  codeLabel: {
    fontSize: 10,
    color: THEME.colors.primary,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  codeDisplay: {
    fontSize: 24,
    fontWeight: '900',
    color: THEME.colors.primary,
    letterSpacing: 4,
    fontFamily: 'monospace',
  },
  codeDisplayEmpty: {
    fontSize: 28,
    fontWeight: '600',
    color: THEME.colors.border,
    letterSpacing: 6,
  },
  feedbackRow: {
    flexDirection: 'row',
    marginTop: 12,
    justifyContent: 'center',
    width: '100%',
    gap: 8,
  },
  feedbackBadge: {
    width: 70,
    backgroundColor: THEME.colors.bgSecondary,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: THEME.colors.bgTertiary,
    elevation: 2,
    shadowColor: THEME.colors.bgTertiary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
  },
  feedbackLabel: {
    fontSize: 11,
    color: THEME.colors.primary,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  feedbackValue: {
    fontSize: 20,
    fontWeight: '900',
    fontFamily: 'monospace',
    color: THEME.colors.primary,
    marginTop: 6,
  },
  codeHint: {
    marginTop: 8,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: THEME.colors.border,
    width: '100%',
  },
  hintText: {
    fontSize: 11,
    color: THEME.colors.textSecondary,
    fontWeight: '600',
    textAlign: 'center',
  },

  // Flux List
  fluxWrapper: {
    flex: 1,
    minHeight: 90,
    borderRadius: 14,
    backgroundColor: THEME.colors.bgSecondary,
    borderWidth: 2,
    borderColor: THEME.colors.primaryLight,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: THEME.colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },

  // Keyboard
  keyboardWrapper: {
    marginBottom: 6,
  },

  resetButton: {
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: 8,
    elevation: 5,
    shadowColor: THEME.colors.success,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  resetGradient: {
    paddingVertical: 15,
    alignItems: 'center',
  },
  resetButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: THEME.colors.white,
    letterSpacing: 0.8,
  },

  // Waiting Room Styles
  waitingRoomContent: {
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 20,
  },
  waitingRoomContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 40,
  },
  waitingTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: THEME.colors.primary,
    marginBottom: 12,
    letterSpacing: 1.2,
    textAlign: 'center',
  },
  waitingSubtitle: {
    fontSize: 13,
    color: THEME.colors.gray200,
    marginBottom: 36,
    letterSpacing: 0.6,
    fontWeight: '600',
  },
  arenaIdSection: {
    backgroundColor: 'rgba(91, 110, 245, 0.1)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 32,
    borderWidth: 1.5,
    borderColor: THEME.colors.primaryLight,
  },
  arenaIdLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: THEME.colors.primary,
    letterSpacing: 0.8,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  arenaIdDisplay: {
    flexDirection: 'row',
    backgroundColor: THEME.colors.bgPrimary,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: THEME.colors.primaryLight,
  },
  arenaIdText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
    color: THEME.colors.primary,
    letterSpacing: 0.5,
    fontFamily: 'monospace',
  },
  copyButton: {
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  copyButtonText: {
    fontSize: 18,
  },
  arenaIdInfo: {
    fontSize: 11,
    color: THEME.colors.textSecondary,
    fontStyle: 'italic',
  },
  downloadPrompt: {
    backgroundColor: 'rgba(249, 115, 22, 0.1)',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginTop: 12,
    borderWidth: 1.5,
    borderColor: THEME.colors.warning,
    alignItems: 'center',
    gap: 8,
  },
  downloadPromptIcon: {
    fontSize: 24,
  },
  downloadPromptText: {
    fontSize: 12,
    color: THEME.colors.warning,
    fontWeight: '700',
    textAlign: 'center',
  },
  downloadPromptButton: {
    backgroundColor: THEME.colors.warning,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginTop: 6,
  },
  downloadPromptButtonText: {
    fontSize: 12,
    fontWeight: '800',
    color: THEME.colors.white,
    letterSpacing: 0.5,
  },
  loadingAnimation: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
    marginBottom: 48,
  },
  loadingDot: {
    fontSize: 32,
    color: THEME.colors.primary,
    opacity: 0.7,
  },
  playersContainer: {
    backgroundColor: THEME.colors.bgSecondary,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: THEME.colors.primaryLight,
    paddingVertical: 20,
    paddingHorizontal: 16,
    marginBottom: 36,
    width: '100%',
    maxWidth: 320,
    elevation: 4,
    shadowColor: THEME.colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
  },
  playersTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: THEME.colors.primary,
    textAlign: 'center',
    marginBottom: 14,
    letterSpacing: 1,
  },
  playerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 10,
    marginBottom: 8,
    backgroundColor: THEME.colors.bgSecondary,
    borderRadius: 10,
    borderLeftWidth: 3,
    borderLeftColor: THEME.colors.primary,
  },
  playerIcon: {
    fontSize: 20,
  },
  playerName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: THEME.colors.textPrimary,
  },
  playerStatus: {
    fontSize: 11,
    color: THEME.colors.primary,
    fontWeight: '700',
    backgroundColor: THEME.colors.bgTertiary,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  emptyPlayerSlot: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(160, 174, 192, 0.1)',
    borderRadius: 8,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: THEME.colors.borderLight,
  },
  emptyPlayerIcon: {
    fontSize: 18,
  },
  emptyPlayerText: {
    fontSize: 12,
    color: THEME.colors.gray200,
    fontWeight: '600',
  },
  waitingButtonsRow: {
    flexDirection: 'row',
    gap: 14,
    width: '100%',
    maxWidth: 320,
  },
  startButton: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: THEME.colors.secondary,
    paddingVertical: 16,
    alignItems: 'center',
    elevation: 5,
    shadowColor: THEME.colors.secondary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
  },
  startButtonDisabled: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: THEME.colors.gray400,
    paddingVertical: 16,
    alignItems: 'center',
    opacity: 0.4,
  },
  startButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: THEME.colors.white,
    letterSpacing: 1,
  },
  cancelButton: {
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 18,
    backgroundColor: THEME.colors.error,
    elevation: 3,
    shadowColor: THEME.colors.error,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  cancelButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: THEME.colors.bgSecondary,
    letterSpacing: 1,
  },

  // Player Selection Styles (MODE LOCAL)
  playerSelectionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 40,
  },
  playerSelectionTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: THEME.colors.primary,
    marginBottom: 8,
    letterSpacing: 1.2,
    textAlign: 'center',
  },
  playerSelectionSubtitle: {
    fontSize: 15,
    color: THEME.colors.textSecondary,
    marginBottom: 36,
    letterSpacing: 0.6,
    fontWeight: '600',
    textAlign: 'center',
  },
  playerInputsContainer: {
    backgroundColor: THEME.colors.bgSecondary,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: THEME.colors.primaryLight,
    paddingVertical: 24,
    paddingHorizontal: 18,
    marginBottom: 36,
    width: '100%',
    maxWidth: 320,
    gap: 18,
    elevation: 4,
    shadowColor: THEME.colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
  },
  playerInputSection: {
    gap: 10,
  },
  playerInputLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: THEME.colors.primary,
    letterSpacing: 0.6,
  },
  playerInput: {
    backgroundColor: THEME.colors.bgPrimary,
    borderWidth: 2,
    borderColor: THEME.colors.primaryLight,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 15,
    fontWeight: '700',
    color: THEME.colors.textPrimary,
  },
  playerButtonsRow: {
    flexDirection: 'row',
    gap: 14,
    width: '100%',
    maxWidth: 320,
  },
  startLocalButton: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: THEME.colors.secondary,
    paddingVertical: 16,
    alignItems: 'center',
    elevation: 5,
    shadowColor: THEME.colors.secondary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
  },
  startLocalButtonDisabled: {
    backgroundColor: THEME.colors.gray200,
    opacity: 0.4,
  },
  startLocalButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: THEME.colors.bgSecondary,
    letterSpacing: 1,
  },
  backButton: {
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: THEME.colors.textMuted,
    elevation: 3,
    shadowColor: THEME.colors.textPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  backButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: THEME.colors.white,
    letterSpacing: 0.8,
  },
  localPlayerIndicator: {
    backgroundColor: THEME.colors.primary,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  currentPlayerLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: THEME.colors.bgSecondary,
    letterSpacing: 0.5,
  },
  difficultyContainer: {
    width: '100%',
    maxWidth: 380,
    marginVertical: 20,
    gap: 16,
    alignSelf: 'center',
    alignItems: 'center',
  },
  difficultySelectionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  difficultyScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  difficultySelectionTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: THEME.colors.primary,
    letterSpacing: 1,
    marginBottom: 8,
  },
  titleIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  difficultyIconWrap: {
    marginBottom: 12,
  },
  difficultyReturnRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  difficultySelectionSubtitle: {
    fontSize: 13,
    color: THEME.colors.textSecondary,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 24,
  },
  difficultyButton: {
    backgroundColor: THEME.colors.bgSecondary,
    borderRadius: 16,
    paddingVertical: 22,
    paddingHorizontal: 24,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: THEME.colors.primaryLight,
    elevation: 4,
    shadowColor: THEME.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    width: '100%',
    maxWidth: 320,
    alignSelf: 'center',
    marginVertical: 6,
  },
  difficultyEmoji: {
    fontSize: 44,
    marginBottom: 12,
  },
  difficultyLevel: {
    fontSize: 17,
    fontWeight: '900',
    color: THEME.colors.primary,
    letterSpacing: 1.2,
    marginBottom: 6,
  },
  difficultyDesc: {
    fontSize: 13,
    color: THEME.colors.textSecondary,
    fontWeight: '500',
  },
  difficultyReturnButton: {
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 24,
    backgroundColor: THEME.colors.textMuted,
    elevation: 3,
    shadowColor: THEME.colors.textPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    marginTop: 24,
  },
  difficultyReturnText: {
    fontSize: 14,
    fontWeight: '800',
    color: THEME.colors.white,
    letterSpacing: 0.8,
  },
});

